### ISSUE TITLE
mpv freezes on Linux Mint 21.1 with audio enabled

### ISSUE THREAD

**Issue by albertescanes** [flathub/io.mpv.Mpv#193]
Hello all,

I detected the following issue with flatpak mpv on Linux Mint 21.1.

When I try to load a video with sound enabled it freezes and does not load the file at all, however, works fine if I run it with no audio and just the video:
![mpv_issue](https://user-images.githubusercontent.com/132266745/235769239-b785ded8-b858-4d80-8d0e-54213e42730f.png)

I tested on another computer with Mint installed and same issue occours.

Attached log:

[log.txt](https://github.com/flathub/io.mpv.Mpv/files/11377240/log.txt)

This does not happen with mpv installed with apt.

I'm not sure if the issue is located on distro or on the flatpak package, so I apologize in advance if I have not reported the issue in the proper place.

Many thanks for your time.

**Comment by kevinlekiller** [comment]
There's not anything in the log that helps figuring what the issue is.

If I were to guess it's something to do with pipewire.

Try with a different `--ao` like `alsa` or `pulse`. 

FWIW, pipewire works fine here, but I've seen people report issues with pipewire on mpv in the past, for example https://github.com/mpv-player/mpv/issues/10912.

**Comment by albertescanes** [comment]
Thank you, `--ao=pulse` fixes the issue. While apt mpv automatically sets pulse as audio driver with no configuration specified, flatpak mpv doesn't.

**Comment by kevinlekiller** [comment]
No worries.

It could be down to some pipewire specific libraries being too modern in the flatpak version of mpv which causes issues with Linux Mint 21.1, but I can't say for sure unfortunately.
