### ISSUE TITLE
mpv_thumbnail_script unable to generate thumbnails

### ISSUE THREAD

**Issue by jamesxmcintosh** [flathub/io.mpv.Mpv#2]
When using [mpv_thumbnail_script](https://github.com/TheAMM/mpv_thumbnail_script) it is unable to generate any thumbnails. At first I thought it was a write permission problem but the script is able to output its error log in the same directory (/tmp/) and if the thumbnails are generated by the native version of mpv the flatpak version is able to display them. 

Is there another permission I need to allow or is it a problem with the script?

[mpv_thumbnail_script error log](https://gist.github.com/jamesxmcintosh/6a6d31e5437f66f2cc8690d89de2228b)

[mpv log file](https://gist.github.com/jamesxmcintosh/04f68406d4c83479b7a3abe551b96be8)

**Comment by fastrizwaan** [comment]
I've tried, copying the lua scripts to `/var/lib/flatpak/app/io.mpv.Mpv/x86_64/stable/c00f5731621a5175e7e47e8b037ef20420c0e98c152df366447ff71651eff161/files/etc/mpv`  (use `sudo find /var -iname 'mpris.so'`)

Also copied the 2 lua scripts from releases to ~/.config/scripts. it is not working for me. 

Have your tried the scripts with non-flatpak version ? Can you share your files with me with local mpv install (not flatpak). If it is working with non-flatpak version, then probably, we can get it working. If it works great, we may include it in the flatpak too.

**Comment by jamesxmcintosh** [comment]
Here are the latest versions of the thumbnail scripts that I have been using. [mpv_thumbnail_script_client_osc](https://gist.github.com/jamesxmcintosh/4224551956f4626df69920750fccf887), [mpv_thumbnail_script_server](https://gist.github.com/jamesxmcintosh/f419785d1c95d8f49873b800bb407dc5).

I have also found that [mpv-webm](https://github.com/ekisu/mpv-webm) and [streamsave](https://github.com/Sagnac/streamsave) are unable to output new files when used with the flatpak version. I have tried placing them in:
 `.var/app/io.mpv.Mpv/config/mpv/scripts/` and `/var/lib/flatpak/app/io.mpv.Mpv/x86_64/stable/c00f5731621a5175e7e47e8b037ef20420c0e98c152df366447ff71651eff161/files/etc/mpv/scripts/`. 

I can confirm that all these scripts work as expected with the native version of mpv.

**Comment by fastrizwaan** [comment]
flatpak mpv is read only, we'll try to give specific directories write permission. What folder/directories needs to be writeable?

In the mean time I'll try your given scripts. If we can get it working with flatpak, then we'll definitely add it to flatpak. Thanks.

**Comment by fastrizwaan** [comment]
Ok, I've added mpv thumbnailer script, please test it `flatpak install https://dl.flathub.org/build-repo/46886/io.mpv.Mpv.flatpakref`

**Comment by jamesxmcintosh** [comment]
The thumbnails works with `flatpak install https://dl.flathub.org/build-repo/46886/io.mpv.Mpv.flatpakref`

I don't know what directories need write permission when encoding new files.

**Comment by fastrizwaan** [comment]
It's updated at flathub also now. also added missing codecs https://flathub.org/apps/details/io.mpv.Mpv.

**Comment by fastrizwaan** [comment]
> I have also found that [mpv-webm](https://github.com/ekisu/mpv-webm) and [streamsave](https://github.com/Sagnac/streamsave) are unable to output new files when used with the flatpak version. I have tried placing them in:

I edited webm.lua
`output_directory = [[~/Pictures/mpv-screenshots]],`

webm.conf
`output_directory=~/Pictures/mpv-screenshots/`

it is encoding to webm. But this requires general write permission, which can be security risk, not because of lua scripts, could be due to mpv. or again we need to add this script to flatpak with `~/Videos/mpv-webm-output` directory; this becomes bloated, instead there are alternative apps at flathub which do the same thing

#### stream save:
https://flathub.org/apps/details/com.github.JannikHv.Gydl
https://flathub.org/apps/details/io.github.JaGoLi.ytdl_gui

or we can save streams using screen recorders, 
https://flathub.org/apps/details/sa.sy.bluerecorder
https://flathub.org/apps/details/io.github.seadve.Kooha

#### and webm 
https://flathub.org/apps/details/com.ozmartians.VidCutter
https://flathub.org/apps/details/no.mifi.losslesscut
https://flathub.org/apps/details/org.gnome.gitlab.YaLTeR.VideoTrimmer

**Comment by jamesxmcintosh** [comment]
Since encoding was enabled these scripts have started working when placed in `.var/app/io.mpv.Mpv/config/mpv/scripts`. I don't think any other changes are needed.

Thanks for your help.
