### ISSUE TITLE
Support XDG_CONFIG_HOME config directory

### ISSUE THREAD

**Issue by Limero** [flathub/io.mpv.Mpv#82]
Is it possible for the XDG_CONFIG_HOME config directory to be mounted inside of this Flatpak by default?

I expected the mpv Flatpak to work as a drop-in replacement for the official package, but the Flatpak reads its config from `~/.var/app/io.mpv.Mpv/config/mpv/` instead of `~/.config/mpv/` meaning I have to symlink or move the config for it to work.

Anything to simplify the process of moving to Flatpak would be great. I think this issue will continue to confuse people reading official mpv documentation and examples where `~/.config` is used.

**Comment by fastrizwaan** [comment]
That's part of container sandboxing. It is expected.

The same behavior can be seen with `org.mozilla.Firefox` flatpak, it uses sandboxed `.mozilla` directory instead of `~/.mozilla` 

E.g, I use separate profiles with  `org.mozilla.firefox` and system firefox (`/usr/bin/firefox`). 

As you know already, symlink it or copy the config files. 

Also, scripts in `~/.config/mpv` will not work with which has hardcoded path to `~/.config/mpv` with flatpak version.

**Comment by Erick555** [comment]
To be clear: every flatpak sets `XDG_CONFIG_HOME` as `~/.var/app/<appid>/config`. Just try `flatpak run --command=sh io.mpv.Mpv` then `printenv XDG_CONFIG_HOME` and see yourself.
